#!/usr/bin/env python3
"""Rebuild references/vault-snapshot.md from the Obsidian vault, then zip the skill for claude.ai.

The vault is the source of truth. The snapshot is the fallback when the vault isn't readable
(claude.ai, another machine). Only notes tagged `voice-sample: true` go in.
The snapshot is gitignored: the repo is public and the vault is private. It ships only in the zip.

Usage: python3 scripts/snapshot.py [vault_path]
"""
import pathlib
import re
import sys
import zipfile

SKILL = pathlib.Path(__file__).resolve().parent.parent
VAULT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "/Users/mikesavoff/Documents/Obsidian Vault")
OUT = SKILL / "references" / "vault-snapshot.md"
ZIP = SKILL.parent / "mike-voice.zip"
EMAIL = re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+")
FM = re.compile(r"\A---\n(.*?)\n---\n", re.S)

notes = []
for path in sorted(VAULT.rglob("*.md")):
    if any(part.startswith(".") for part in path.relative_to(VAULT).parts):
        continue
    text = path.read_text()
    m = FM.match(text)
    if not m or "voice-sample: true" not in m.group(1):
        continue
    register = re.search(r"voice-register: (\S+)", m.group(1))
    body = EMAIL.sub("[email removed]", text[m.end():].strip())
    notes.append((path.relative_to(VAULT), register.group(1) if register else "?", body))

# Published pieces first: they are the strongest evidence of the finished voice.
notes.sort(key=lambda n: (not str(n[0]).startswith(("linkedin posts", "copy")), str(n[0])))

parts = [
    "# Vault snapshot",
    "",
    "Generated by `scripts/snapshot.py`. Do not edit by hand: edit the vault and rerun.",
    "Use this only when the vault isn't readable. Verbatim, only `voice-sample: true` notes.",
]
for rel, register, body in notes:
    parts += ["", "---", "", f"## {rel} ({register})", "", body]
OUT.write_text("\n".join(parts) + "\n")

with zipfile.ZipFile(ZIP, "w", zipfile.ZIP_DEFLATED) as z:
    for f in SKILL.rglob("*"):
        if f.is_file() and "__pycache__" not in f.parts:
            z.write(f, pathlib.Path("mike-voice") / f.relative_to(SKILL))

print(f"{len(notes)} notes -> {OUT.relative_to(SKILL.parent.parent.parent)}")
print(f"zip -> {ZIP}")
